### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by thisisritz**
fixed selector for magnet link

### CODE REVIEW

**Comment by c0b41** [comment]
thanks

**Comment by kiriles90** [comment]
@fontanierh @c0b41 

Any chance that someone can fix this again now with the variable selectors 1337x has implemented? I've tried but I lack the required skill to do so.

**Comment by c0b41** [comment]
@kiriles90 sorry for the delay, update xtorrent@^0.2.4

**Comment by kiriles90** [comment]
Thank you!!

**Pull request merged**
